logging:
  enabled: true             # Device results still stream to stdout, even if its disabled.

max_workers: 30              # Maximum concurrent IP/device processing

discovery:
  enabled: true              # Enable discovery mode

metrics:
  enabled: true              # Enable metrics mode
