logging:
  enabled: true             # Device results still stream to stdout, even if its disabled.

timing:
  enabled: true              # Enable Go-side timestamp and duration calculation

max_workers: 30

discovery:
  enabled: true
  timeout_seconds: 30        # Overall timeout per IP (seconds)
  connection_timeout: 10     # Timeout per credential attempt (seconds) - matches Java default

metrics:
  enabled: true
  timeout_seconds: 60        # Overall timeout per device (seconds)
  connection_timeout: 10     # Timeout per device connection attempt (seconds)
